Fix Caps Lock LED not working properly.
acidanthera/VoodooPS2 pull request #7
Opened 2020-01-24 14:42 UTC by Goshin

Hi,

#3 fixed the Caps Lock functionality, but the LED still works in a strange way.

The LED is always lighted when the caps lock is pressed and turns off when it is released, just like a blink.

In the log:
```shell
kernel: (kernel) ApplePS2Keyboard: Caps Lock goingDown: 0x1 # pressed
kernel: (kernel) ApplePS2Keyboard: setAlphaLockFeedback locked:0x1 # turn on LED, should be ignored
kernel: (kernel) ApplePS2Keyboard: setAlphaLockFeedback locked:0x1 # This is the true state change.
kernel: (kernel) ApplePS2Keyboard: Caps Lock goingDown: 0x0 #released
kernel: (kernel) ApplePS2Keyboard: setAlphaLockFeedback locked:0x0 # turn off LED, should be ignored
```

The true state change for LED was overridden in the period.

This fix is to ignore the LED changes after caps lock key going down and going up.
It should work for both a long press and a short press when changing caps state and input source.

Note that there seems to be a system bug for Catalina. The caps state LED doesn't work sometimes. You may need to toggle (enable and disable) the option in `Keyboard -> Input Sources -> Use the Caps Lock key to switch ...`.

2020-01-25 16:40 UTC, NMAC427 approved these changes

2020-01-27 08:25 UTC, usr-sse2 requested changes
Thank you for your excellent work! This fix works correctly in both language switching and caps lock modes, even when swapping Caps Lock with some other modifier key like Control.
Please fix the spelling in your code before I merge this pull request (`_ignoreCapsLedChagnge` should be spelled `_ignoreCapsLedChange`, without extra `g`).

2020-01-27 09:38 UTC, vit9696 commented
Looks like there is still one more left:
https://travis-ci.com/acidanthera/VoodooPS2/jobs/280374759#L196

2020-01-27 09:39 UTC, vit9696 commented
REF: https://github.com/acidanthera/bugtracker/issues/514

2020-01-27 09:42 UTC, Goshin commented
> Looks like there is still one more left:
> https://travis-ci.com/acidanthera/VoodooPS2/jobs/280374759#L196

Thank you so much for your careful review.

2020-01-27 10:00 UTC, merged

2020-02-04 13:10 UTC, Mateo1234454545 commented
Problem still exists on latest release.

2020-02-04 13:30 UTC, Goshin commented
> Problem still exists on latest release.

Use the debug kext and see if you can get some log when switching the caps lock.

2020-02-04 18:00 UTC, Mateo1234454545 commented
> > Problem still exists on latest release.
> 
> Use the debug kext and see if you can get some log when switching the caps lock.

![Screen Shot 2020-02-04 at 19 58 27](https://user-images.githubusercontent.com/42322772/73772447-d1405500-4788-11ea-87af-936c5dafa415.png)

2020-02-04 18:28 UTC, Goshin commented
@Mateo1234454545 
Well, it seems the debug version does not define the DEBUG_MSG Marco, so it does not print the log we want. Try this one:

[VoodooPS2Controller-2.1.1-RELEASE.zip](https://github.com/acidanthera/VoodooPS2/files/4155177/VoodooPS2Controller-2.1.1-RELEASE.zip)

btw what is your OS version?

2020-02-04 18:43 UTC, Mateo1234454545 commented
Will try tomorrow.
I'm on Catalina 10.15.3

2020-08-29 18:08 UTC, Mateo1234454545 commented
Problem is more obvious on Big Sur.
Hope someone fixes it soon.